HOST = 140.113.24.241
IMG_INPUT = ../source/doll/Matryoshka\ dolls.jpg
IMG_OUTPUT = output.png

all:
	chmod +x *.py
run:
	./1-1.py $(HOST) 30170
#	./1-2.py $(HOST) 30171
	./1-3.py $(HOST) 30173
	./1-4.py $(IMG_INPUT)
	./2-1.py $(HOST) 30172
	./2-2.py $(HOST) 30174
clean:
	rm $(IMG_OUTPUT)
